# Generated by Django 6.0.6 on 2026-06-19 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseDeces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_cim', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pays', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('etablissement', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_deces', models.DateField()),
                ('heure_deces', models.TimeField(blank=True, null=True)),
                ('type_deces', models.CharField(choices=[('NATUREL', 'Naturel'), ('ACCIDENT', 'Accident'), ('INCONNU', 'Inconnu')], max_length=20)),
                ('certificat_medical', models.BooleanField(default=False)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deces', to='deces.causedeces')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_enregistres', to=settings.AUTH_USER_MODEL)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deces', to='deces.lieu')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deces', to='deces.personne')),
            ],
        ),
    ]
